### ISSUE TITLE
Add VizSec2021

### ISSUE THREAD

**Issue by bof64665** [f2cx/vizsec-papers#1]
Hi,

not a real "issue" but just wanting to get in touch that I would have the files etc. for VizSec 2021 somehow ready and would like to contribute. I could create a PR from a fork but just wanting to make sure the way you would like to proceed.

**Comment by f2cx** [comment]
Thanks for getting in touch and your offer to contribute. I have actually updated the website in the meanwhile. Will push it to this repository soon as well.
